# KTSB — Hardware detection + docker-compose.override.yml generator (Windows/PowerShell)
# Run this once before "docker compose up" to enable GPU support.
# Safe to run again at any time to refresh detection.

$ScriptDir = Split-Path -Parent $MyInvocation.MyCommand.Path
$StateDir = Join-Path $ScriptDir "state"
$OverrideFile = Join-Path $ScriptDir "docker-compose.override.yml"
$HwFile = Join-Path $StateDir "hardware.json"

New-Item -ItemType Directory -Force -Path $StateDir | Out-Null

Write-Host ""
Write-Host "=== KTSB Hardware Detection ===" -ForegroundColor Cyan
Write-Host ""

# ── CPU ───────────────────────────────────────────────────────────────────────
$cpu = Get-CimInstance Win32_Processor | Select-Object -First 1
$cpuModel = $cpu.Name.Trim()
$cpuCores = $cpu.NumberOfLogicalProcessors
Write-Host "  CPU:  $cpuModel ($cpuCores cores)"

# ── RAM ───────────────────────────────────────────────────────────────────────
$cs = Get-CimInstance Win32_ComputerSystem
$ramGb = [math]::Round($cs.TotalPhysicalMemory / 1GB, 1)
Write-Host "  RAM:  $ramGb GB"

# ── GPU detection ─────────────────────────────────────────────────────────────
$gpuType = "none"
$gpuName = ""
$gpuVramGb = $null
$gpusJson = "[]"

# NVIDIA via nvidia-smi
$nvidiaSmi = Get-Command "nvidia-smi" -ErrorAction SilentlyContinue
if ($nvidiaSmi) {
    $nvidiaOut = & nvidia-smi --query-gpu=name,memory.total --format=csv,noheader,nounits 2>$null
    if ($LASTEXITCODE -eq 0 -and $nvidiaOut) {
        $firstLine = ($nvidiaOut -split "`n")[0].Trim()
        $parts = $firstLine -split ","
        $gpuType = "nvidia"
        $gpuName = $parts[0].Trim()
        $vramMb = [int]$parts[1].Trim()
        $gpuVramGb = [math]::Round($vramMb / 1024, 1)
        $gpusJson = "[{`"type`": `"nvidia`", `"id`": 0, `"name`": `"$gpuName`", `"vram_gb`": $gpuVramGb}]"
        Write-Host "  GPU:  NVIDIA $gpuName ($gpuVramGb GB VRAM)" -ForegroundColor Green
    }
}

# AMD via Windows WMI
if ($gpuType -eq "none") {
    $gpus = Get-CimInstance Win32_VideoController | Where-Object { $_.Name -match "AMD|Radeon|RX " }
    if ($gpus) {
        $gpuType = "amd"
        $gpuName = $gpus[0].Name
        $gpusJson = "[{`"type`": `"amd`", `"id`": 0, `"name`": `"$gpuName`", `"vram_gb`": null}]"
        Write-Host "  GPU:  AMD $gpuName" -ForegroundColor Green
    }
}

# Intel via Windows WMI
if ($gpuType -eq "none") {
    $gpus = Get-CimInstance Win32_VideoController | Where-Object { $_.Name -match "Intel" }
    if ($gpus) {
        $gpuType = "intel"
        $gpuName = $gpus[0].Name
        $gpusJson = "[{`"type`": `"intel`", `"id`": 0, `"name`": `"$gpuName`", `"vram_gb`": null}]"
        Write-Host "  GPU:  Intel $gpuName" -ForegroundColor Yellow
    }
}

if ($gpuType -eq "none") {
    Write-Host "  GPU:  None detected (CPU mode)"
}

# ── WSL2 CUDA check (NVIDIA only) ────────────────────────────────────────────
$wsl2CudaOk = $false
if ($gpuType -eq "nvidia") {
    $wslLib = "\\wsl$\Ubuntu\usr\lib\wsl\lib\libcuda.so.1"
    if (Test-Path $wslLib) {
        $wsl2CudaOk = $true
        Write-Host "  WSL2: CUDA library found" -ForegroundColor Green
    } else {
        Write-Host "  WSL2: CUDA library NOT found — GPU passthrough may not work" -ForegroundColor Red
        Write-Host "        Install: https://developer.nvidia.com/cuda/wsl" -ForegroundColor Yellow
    }
}

Write-Host ""

# ── Write state/hardware.json ─────────────────────────────────────────────────
$timestamp = (Get-Date).ToUniversalTime().ToString("yyyy-MM-ddTHH:mm:ssZ")
$hwJson = @"
{
  "detected_at": "$timestamp",
  "source": "host_script",
  "platform": "windows",
  "cpu": {
    "model": "$($cpuModel -replace '"', '')",
    "cores": $cpuCores
  },
  "ram_gb": $ramGb,
  "gpus": $gpusJson,
  "npu": { "detected": false }
}
"@
Set-Content -Path $HwFile -Value $hwJson -Encoding UTF8
Write-Host "  Hardware info saved to: state\hardware.json"
Write-Host ""

# ── Generate docker-compose.override.yml ─────────────────────────────────────
if ($gpuType -eq "nvidia") {
    $override = @"
# Auto-generated by setup.ps1 -- NVIDIA GPU detected.
# Adds GPU passthrough to Ollama.
# Requirements: nvidia-container-toolkit + WSL2 CUDA driver.
services:
  ollama:
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
"@
    Set-Content -Path $OverrideFile -Value $override -Encoding UTF8
    Write-Host "  OK docker-compose.override.yml written (NVIDIA GPU enabled for Ollama)" -ForegroundColor Green

    if (-not $wsl2CudaOk) {
        Write-Host ""
        Write-Host "  WARNING: WSL2 CUDA library not found. GPU passthrough will likely fail." -ForegroundColor Red
        Write-Host "  Install WSL2 CUDA driver from: https://developer.nvidia.com/cuda/wsl" -ForegroundColor Yellow
    }

} elseif ($gpuType -eq "amd") {
    Write-Host "  NOTE: AMD GPU detected. ROCm GPU passthrough on Windows/Docker is not yet supported." -ForegroundColor Yellow
    Write-Host "        Ollama will run in CPU mode. Running on Linux is recommended for AMD GPU support." -ForegroundColor Yellow
    if (Test-Path $OverrideFile) { Remove-Item $OverrideFile }

} else {
    if (Test-Path $OverrideFile) {
        Remove-Item $OverrideFile
        Write-Host "  docker-compose.override.yml removed (CPU mode)" -ForegroundColor Green
    } else {
        Write-Host "  Running in CPU mode (no GPU override needed)" -ForegroundColor Green
    }
}

Write-Host ""
Write-Host "=== LLM source ===" -ForegroundColor Cyan
Write-Host ""
Write-Host "  Kåre needs a language model (LLM) to work."
Write-Host "  The built-in Ollama downloads a ~10 GB Docker image."
Write-Host "  Skip this if you have Ollama or another LLM server already running."
Write-Host ""
$ollamaChoice = Read-Host "  Include built-in Ollama? [Y/n]"
if ([string]::IsNullOrWhiteSpace($ollamaChoice)) { $ollamaChoice = "y" }
Write-Host ""

# ── Write .env ────────────────────────────────────────────────────────────────
$EnvFile = Join-Path $ScriptDir ".env"
if (-not (Test-Path $EnvFile)) {
    $exampleFile = Join-Path $ScriptDir ".env.example"
    if (Test-Path $exampleFile) {
        Copy-Item $exampleFile $EnvFile
        Write-Host "  OK .env created from .env.example" -ForegroundColor Green
    }
}

# Build COMPOSE_PROFILES
$profiles = "medium"
if ($gpuType -eq "nvidia" -or $gpuType -eq "amd" -or $gpuType -eq "intel") {
    $profiles = "full"
}
if ($ollamaChoice -match "^[Yy]") {
    $profiles = "ollama,$profiles"
}

# Update COMPOSE_PROFILES in .env
if (Test-Path $EnvFile) {
    $envContent = Get-Content $EnvFile
    $updated = $false
    $newContent = $envContent | ForEach-Object {
        if ($_ -match "^COMPOSE_PROFILES=") {
            "COMPOSE_PROFILES=$profiles"
            $updated = $true
        } else { $_ }
    }
    if (-not $updated) { $newContent += "COMPOSE_PROFILES=$profiles" }
    Set-Content -Path $EnvFile -Value $newContent -Encoding UTF8
    Write-Host "  OK COMPOSE_PROFILES=$profiles written to .env" -ForegroundColor Green
}

Write-Host ""
Write-Host "=== Next steps ===" -ForegroundColor Cyan
Write-Host ""
Write-Host "  docker compose up -d"
Write-Host ""
