#!/usr/bin/env bash
# KTSB — Hardware detection + docker-compose.override.yml generator
# Run this once before "docker compose up" to enable GPU support.
# Safe to run again at any time to refresh detection.

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
STATE_DIR="$SCRIPT_DIR/state"
OVERRIDE_FILE="$SCRIPT_DIR/docker-compose.override.yml"
HW_FILE="$STATE_DIR/hardware.json"

mkdir -p "$STATE_DIR"

echo ""
echo "=== KTSB Hardware Detection ==="
echo ""

# ── Platform ─────────────────────────────────────────────────────────────────
PLATFORM="linux"
if [[ "$(uname -s)" == "Darwin" ]]; then
  PLATFORM="darwin"
fi

# ── CPU ──────────────────────────────────────────────────────────────────────
CPU_MODEL="unknown"
CPU_CORES=0
if [[ -f /proc/cpuinfo ]]; then
  CPU_MODEL=$(grep -m1 "^model name" /proc/cpuinfo | cut -d: -f2 | xargs)
  CPU_CORES=$(grep -c "^processor" /proc/cpuinfo || echo 0)
elif [[ "$PLATFORM" == "darwin" ]]; then
  CPU_MODEL=$(sysctl -n machdep.cpu.brand_string 2>/dev/null || echo "unknown")
  CPU_CORES=$(sysctl -n hw.logicalcpu 2>/dev/null || echo 0)
fi
echo "  CPU:  $CPU_MODEL ($CPU_CORES cores)"

# ── RAM ──────────────────────────────────────────────────────────────────────
RAM_GB=0
if [[ -f /proc/meminfo ]]; then
  RAM_KB=$(grep "^MemTotal:" /proc/meminfo | awk '{print $2}')
  RAM_GB=$(echo "scale=1; $RAM_KB / 1048576" | bc 2>/dev/null || echo 0)
elif [[ "$PLATFORM" == "darwin" ]]; then
  RAM_BYTES=$(sysctl -n hw.memsize 2>/dev/null || echo 0)
  RAM_GB=$(echo "scale=1; $RAM_BYTES / 1073741824" | bc 2>/dev/null || echo 0)
fi
echo "  RAM:  ${RAM_GB} GB"

# ── GPU detection ─────────────────────────────────────────────────────────────
GPU_TYPE="none"
GPU_NAME=""
GPU_VRAM_GB=""

# NVIDIA
if command -v nvidia-smi &>/dev/null; then
  NVIDIA_OUT=$(nvidia-smi --query-gpu=name,memory.total --format=csv,noheader,nounits 2>/dev/null || true)
  if [[ -n "$NVIDIA_OUT" ]]; then
    GPU_TYPE="nvidia"
    GPU_NAME=$(echo "$NVIDIA_OUT" | head -1 | cut -d, -f1 | xargs)
    VRAM_MB=$(echo "$NVIDIA_OUT" | head -1 | cut -d, -f2 | xargs)
    GPU_VRAM_GB=$(echo "scale=1; $VRAM_MB / 1024" | bc 2>/dev/null || echo "?")
    echo "  GPU:  NVIDIA $GPU_NAME (${GPU_VRAM_GB} GB VRAM)"
  fi
fi

# AMD (rocm-smi)
if [[ "$GPU_TYPE" == "none" ]] && command -v rocm-smi &>/dev/null; then
  ROCM_OUT=$(rocm-smi --showproductname 2>/dev/null || true)
  if echo "$ROCM_OUT" | grep -qi "card"; then
    GPU_TYPE="amd"
    GPU_NAME=$(echo "$ROCM_OUT" | grep -i "card" | head -1 | awk '{print $NF}')
    echo "  GPU:  AMD $GPU_NAME"
  fi
fi

# Intel Arc / iGPU
if [[ "$GPU_TYPE" == "none" ]] && [[ -d /sys/class/drm ]]; then
  for uevent in /sys/class/drm/*/device/uevent; do
    if [[ -f "$uevent" ]] && grep -qi "intel\|i915" "$uevent" 2>/dev/null; then
      GPU_TYPE="intel"
      GPU_NAME="Intel GPU"
      echo "  GPU:  Intel GPU detected"
      break
    fi
  done
fi

if [[ "$GPU_TYPE" == "none" ]]; then
  echo "  GPU:  None detected (CPU mode)"
fi

# ── NPU ──────────────────────────────────────────────────────────────────────
NPU_DETECTED=false
if [[ -d /dev/accel ]] && [[ -n "$(ls /dev/accel/ 2>/dev/null)" ]]; then
  NPU_DETECTED=true
  echo "  NPU:  Intel NPU detected ($(ls /dev/accel/ | tr '\n' ' '))"
else
  echo "  NPU:  None detected"
fi

echo ""

# ── Ollama choice ─────────────────────────────────────────────────────────────
echo "=== LLM source ==="
echo ""
echo "  Kåre needs a language model (LLM) to work."
echo "  The built-in Ollama downloads a ~10 GB Docker image."
echo "  Skip this if you have Ollama or another LLM server already running."
echo ""
read -rp "  Include built-in Ollama? [Y/n]: " OLLAMA_CHOICE
OLLAMA_CHOICE="${OLLAMA_CHOICE:-y}"
echo ""

# ── Write state/hardware.json ─────────────────────────────────────────────────
cat > "$HW_FILE" <<EOF
{
  "detected_at": "$(date -u +%Y-%m-%dT%H:%M:%SZ)",
  "source": "host_script",
  "platform": "$PLATFORM",
  "cpu": {
    "model": "$CPU_MODEL",
    "cores": $CPU_CORES
  },
  "ram_gb": $RAM_GB,
  "gpus": $(
    if [[ "$GPU_TYPE" != "none" ]]; then
      echo "[{\"type\": \"$GPU_TYPE\", \"id\": 0, \"name\": \"$GPU_NAME\", \"vram_gb\": $(echo $GPU_VRAM_GB | grep -oP '[\d.]+' || echo 'null')}]"
    else
      echo "[]"
    fi
  ),
  "npu": { "detected": $NPU_DETECTED }
}
EOF

echo "  Hardware info saved to: state/hardware.json"
echo ""

# ── Generate docker-compose.override.yml ─────────────────────────────────────
if [[ "$GPU_TYPE" == "nvidia" ]]; then
  cat > "$OVERRIDE_FILE" <<'OVERRIDE'
# Auto-generated by setup.sh — NVIDIA GPU detected.
# Adds GPU passthrough to Ollama.
# Requirements: nvidia-container-toolkit must be installed on the host.
services:
  ollama:
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
OVERRIDE
  echo "  ✓ docker-compose.override.yml written (NVIDIA GPU enabled for Ollama)"

elif [[ "$GPU_TYPE" == "amd" ]]; then
  cat > "$OVERRIDE_FILE" <<'OVERRIDE'
# Auto-generated by setup.sh — AMD GPU detected.
# Adds ROCm device passthrough to Ollama.
services:
  ollama:
    devices:
      - /dev/kfd
      - /dev/dri
    environment:
      - HSA_OVERRIDE_GFX_VERSION=10.3.0
OVERRIDE
  echo "  ✓ docker-compose.override.yml written (AMD GPU enabled for Ollama)"

elif [[ "$GPU_TYPE" == "intel" ]]; then
  cat > "$OVERRIDE_FILE" <<'OVERRIDE'
# Auto-generated by setup.sh — Intel GPU detected.
# Adds Intel GPU device passthrough to Ollama.
services:
  ollama:
    devices:
      - /dev/dri
    environment:
      - OLLAMA_INTEL_GPU=1
OVERRIDE
  echo "  ✓ docker-compose.override.yml written (Intel GPU enabled for Ollama)"

else
  # Remove override if no GPU (CPU mode)
  if [[ -f "$OVERRIDE_FILE" ]]; then
    rm "$OVERRIDE_FILE"
    echo "  ✓ docker-compose.override.yml removed (CPU mode)"
  else
    echo "  ✓ Running in CPU mode (no GPU override needed)"
  fi
fi

# ── Write .env ────────────────────────────────────────────────────────────────
ENV_FILE="$SCRIPT_DIR/.env"
if [[ ! -f "$ENV_FILE" ]]; then
  cp "$SCRIPT_DIR/.env.example" "$ENV_FILE"
  echo "  ✓ .env created from .env.example"
fi

# Build COMPOSE_PROFILES value
PROFILES="medium"
if [[ "$GPU_TYPE" != "none" ]]; then
  PROFILES="full"
fi
if [[ "${OLLAMA_CHOICE,,}" == "y" || "${OLLAMA_CHOICE,,}" == "yes" || "$OLLAMA_CHOICE" == "" ]]; then
  PROFILES="ollama,$PROFILES"
fi

# Update COMPOSE_PROFILES in .env
if grep -q "^COMPOSE_PROFILES=" "$ENV_FILE"; then
  sed -i "s|^COMPOSE_PROFILES=.*|COMPOSE_PROFILES=$PROFILES|" "$ENV_FILE"
else
  echo "COMPOSE_PROFILES=$PROFILES" >> "$ENV_FILE"
fi
echo "  ✓ COMPOSE_PROFILES=$PROFILES written to .env"

echo ""
echo "=== Next steps ==="
echo ""
echo "  docker compose up -d"
echo ""
if [[ "$GPU_TYPE" == "nvidia" ]]; then
  echo "  NOTE: NVIDIA GPU support requires nvidia-container-toolkit."
  echo "  Install guide: https://docs.nvidia.com/datacenter/cloud-native/container-toolkit/install-guide.html"
  echo ""
fi
