# /kaare/kaare_core/image_store.py
"""
Per-user image storage with automatic rotation.

Directory layout:
  state/images/{user_id}/input/   ← images sent by the user
  state/images/{user_id}/output/  ← images generated by Kåre

Rotation is triggered on every save:
  - If total file count  > images.max_per_user_count → delete oldest files until under limit
  - If total size in MB  > images.max_per_user_mb    → delete oldest files until under limit

Config is read from configs/settings.yaml under the `images:` key.
Defaults: max_per_user_count=500, max_per_user_mb=200.

Image IDs are globally unique (timestamp_uuid8) so /api/image/{id} can find
them by scanning all user folders without a database index.
"""

import base64
import time
import uuid
import logging
from pathlib import Path
from typing import Literal

import yaml

_log = logging.getLogger(__name__)

_IMAGES_ROOT = Path("/kaare/state/images")
_SETTINGS_PATH = Path("/kaare/configs/settings.yaml")

_DEFAULT_MAX_COUNT = 500
_DEFAULT_MAX_MB    = 200


def _load_limits() -> tuple[int, float]:
    try:
        cfg = yaml.safe_load(_SETTINGS_PATH.read_text(encoding="utf-8")) or {}
        img = cfg.get("images", {})
        return int(img.get("max_per_user_count", _DEFAULT_MAX_COUNT)), float(img.get("max_per_user_mb", _DEFAULT_MAX_MB))
    except Exception:
        return _DEFAULT_MAX_COUNT, float(_DEFAULT_MAX_MB)


def _user_dir(user_id: str) -> Path:
    safe = "".join(c for c in user_id if c.isalnum() or c in "_-") or "global"
    return _IMAGES_ROOT / safe


def _all_files_sorted(user_id: str) -> list[Path]:
    """All image files for a user, sorted oldest-first by filename (timestamp prefix)."""
    d = _user_dir(user_id)
    files = list(d.rglob("*.png")) + list(d.rglob("*.jpg")) + list(d.rglob("*.jpeg")) + list(d.rglob("*.webp"))
    return sorted(files, key=lambda p: p.name)


def _rotate(user_id: str) -> None:
    max_count, max_mb = _load_limits()
    files = _all_files_sorted(user_id)

    total_bytes = sum(f.stat().st_size for f in files if f.exists())
    total_mb = total_bytes / (1024 * 1024)

    while files and (len(files) > max_count or total_mb > max_mb):
        oldest = files.pop(0)
        try:
            size = oldest.stat().st_size
            oldest.unlink()
            total_mb -= size / (1024 * 1024)
            _log.info("image_store rotate: deleted %s", oldest)
        except Exception as e:
            _log.warning("image_store rotate error: %s", e)


def _new_image_id() -> str:
    return f"{int(time.time())}_{uuid.uuid4().hex[:8]}"


def save_image(
    data: bytes | str,
    user_id: str,
    folder: Literal["input", "output"],
    ext: str = "png",
) -> str:
    """
    Save an image for a user. data can be raw bytes or a base64 string.
    Returns image_id (used in /api/image/{image_id}).
    """
    raw = base64.b64decode(data) if isinstance(data, str) else data
    image_id = _new_image_id()
    dest_dir = _user_dir(user_id) / folder
    dest_dir.mkdir(parents=True, exist_ok=True)
    (dest_dir / f"{image_id}.{ext}").write_bytes(raw)
    _rotate(user_id)
    return image_id


def find_image(image_id: str) -> Path | None:
    """Search all user folders for an image by ID. Returns Path or None."""
    safe_id = "".join(c for c in image_id if c.isalnum() or c in "_-")
    for ext in ("png", "jpg", "jpeg", "webp"):
        for p in _IMAGES_ROOT.rglob(f"{safe_id}.{ext}"):
            if p.is_file():
                return p
    # Legacy fallback: old state/generated_images/ directory
    legacy = Path("/kaare/state/generated_images") / f"{safe_id}.png"
    if legacy.is_file():
        return legacy
    return None


def list_images(user_id: str, folder: Literal["input", "output", "all"] = "all", limit: int = 20) -> list[dict]:
    """
    List images for a user. Returns list of dicts with id, folder, timestamp, size_kb.
    Sorted newest-first.
    """
    d = _user_dir(user_id)
    folders = ["input", "output"] if folder == "all" else [folder]
    result = []
    for f in folders:
        fdir = d / f
        if not fdir.exists():
            continue
        for p in fdir.iterdir():
            if p.suffix.lower() in (".png", ".jpg", ".jpeg", ".webp"):
                stem = p.stem  # e.g. "1746123456_ab12cd34"
                result.append({
                    "id": stem,
                    "folder": f,
                    "filename": p.name,
                    "size_kb": round(p.stat().st_size / 1024, 1),
                    "path": str(p),
                })
    result.sort(key=lambda x: x["id"], reverse=True)
    return result[:limit]


def storage_stats(user_id: str) -> dict:
    """Return count and total MB for a user."""
    files = _all_files_sorted(user_id)
    total_bytes = sum(f.stat().st_size for f in files if f.exists())
    return {
        "user_id": user_id,
        "count": len(files),
        "mb": round(total_bytes / (1024 * 1024), 2),
    }


def all_users_stats() -> list[dict]:
    """Return storage stats for all users."""
    if not _IMAGES_ROOT.exists():
        return []
    result = []
    for d in _IMAGES_ROOT.iterdir():
        if d.is_dir():
            result.append(storage_stats(d.name))
    return sorted(result, key=lambda x: x["mb"], reverse=True)
