import asyncio
import logging
import re
import time
from datetime import datetime
from pathlib import Path

import kaare_core.app_state as app_state
from adapters.llm_adapter import ask_llm_with_tools

_log = logging.getLogger("kaare_api")

_JANG_LAST_READ_PATH = Path("/kaare/state/jang_last_read.txt")
_JANG_TS_RE = re.compile(r"^\[Jang (\d{4}-\d{2}-\d{2} \d{2}:\d{2})\]")
_MEETING_LOCK = Path("/kaare/state/meeting_active.lock")

_JANG_TOOLS: list | None = None


def _get_jang_tools() -> list:
    global _JANG_TOOLS
    if _JANG_TOOLS is None:
        from kaare_core.tools.definitions import get_tools
        allowed = {
            "self_image", "note",
            "selvbilde", "notat",
        }
        _JANG_TOOLS = [t for t in get_tools("nb") if t.get("function", {}).get("name") in allowed]
    return _JANG_TOOLS


def _in_meeting_blackout() -> bool:
    if not _MEETING_LOCK.exists():
        return False
    age_seconds = time.time() - _MEETING_LOCK.stat().st_mtime
    if age_seconds > 10800:
        try:
            _MEETING_LOCK.unlink(missing_ok=True)
            _log.warning(
                "meeting_active.lock was %.0f hours old — removed as stale", age_seconds / 3600
            )
        except Exception:
            pass
        return False
    return True


def _read_jang_last_read() -> datetime | None:
    try:
        return datetime.fromisoformat(_JANG_LAST_READ_PATH.read_text(encoding="utf-8").strip())
    except Exception:
        return None


def _write_jang_last_read() -> None:
    try:
        from kaare_core.config import get_local_tz as _get_local_tz
        _JANG_LAST_READ_PATH.write_text(
            datetime.now(tz=_get_local_tz()).isoformat(timespec="seconds"), encoding="utf-8"
        )
    except Exception as e:
        _log.warning("jang_reflection: could not write last_read: %s", e)


def _filter_new_thoughts(text: str, since: datetime | None) -> str:
    if since is None:
        return text

    from kaare_core.config import get_local_tz as _get_local_tz
    local_tz = _get_local_tz()

    entries: list[str] = []
    current_lines: list[str] = []
    current_ts: datetime | None = None

    for line in text.splitlines():
        m = _JANG_TS_RE.match(line)
        if m:
            if current_lines and current_ts and current_ts > since:
                entries.append("\n".join(current_lines))
            try:
                current_ts = datetime.strptime(m.group(1), "%Y-%m-%d %H:%M").replace(tzinfo=local_tz)
            except ValueError:
                current_ts = None
            current_lines = [line]
        else:
            current_lines.append(line)

    if current_lines and current_ts and current_ts > since:
        entries.append("\n".join(current_lines))

    return "\n\n".join(entries)


async def _run_jang_reflection() -> None:
    thoughts_path = Path("/kaare/state/inner_thoughts.txt")
    if not thoughts_path.exists() or not thoughts_path.stat().st_size:
        return

    try:
        raw_text = thoughts_path.read_text(encoding="utf-8").strip()
    except Exception as e:
        _log.warning("jang_reflection: could not read inner_thoughts: %s", e)
        return

    if not raw_text:
        return

    since = _read_jang_last_read()
    thoughts = _filter_new_thoughts(raw_text, since)

    app_state._last_jang_run_time = time.time()

    if not thoughts.strip():
        return

    _write_jang_last_read()
    print("[KÅRE REFLECTION] Starting internal reflection cycle")

    micro_prompt = (
        "This is a private internal reflection session. No user is present.\n\n"
        "The following new thoughts were generated by Jing and Jang, your inner voices:\n\n"
        f"{thoughts}\n\n"
        "Review these thoughts. Consider:\n"
        "- Does anything reveal something genuine about who you are or how you function? → oppdater_selvbilde\n"
        "- Is there a thought worth keeping as a note for later? → skriv_notat\n"
        "Only use tools if there is something genuinely worth doing. "
        "Trivial or already-known things do not need action. "
        "When done, respond briefly in Norwegian with what you did, or 'Ingen endringer.' if nothing was needed."
    )

    messages = [{"role": "user", "content": micro_prompt}]
    tools = _get_jang_tools()

    from kaare_core.tools.executor import execute_tool

    for _round in range(3):
        try:
            result = await ask_llm_with_tools(
                messages=messages,
                tools=tools,
                rid=f"rid-refl-{int(time.time()*1000)}",
                user_id="kare",
            )
        except Exception as e:
            _log.warning("jang_reflection: ask_llm_with_tools failed: %s", e)
            break

        tool_calls = result.get("tool_calls")
        if not tool_calls:
            print(f"[KÅRE REFLECTION] Reflection done. response={((result.get('text') or '')[:160])!r}")
            break

        messages.append({
            "role": "assistant",
            "content": result.get("text") or "",
            "tool_calls": tool_calls,
        })

        for tc in tool_calls:
            fn = tc.get("function", {})
            name = fn.get("name", "")
            args = fn.get("arguments", {})
            print(f"[KÅRE REFLECTION] Tool call: {name}  args={str(args)[:120]}")
            try:
                tool_result = await execute_tool(name, args)
            except Exception as e:
                tool_result = f"Tool error: {e}"
            messages.append({"role": "tool", "name": name, "content": str(tool_result)})

    print("[KÅRE REFLECTION] Reflection cycle complete")


async def start_reflection_loop() -> None:
    await asyncio.sleep(120)  # let startup settle

    while True:
        await asyncio.sleep(60)
        try:
            if not app_state._REFLECTION_ENABLED:
                continue
            now = time.time()
            if now - app_state._last_jang_run_time < app_state._JANG_INTERVAL_S:
                continue
            if now - app_state._last_user_prompt_time < app_state._JANG_INTERVAL_S - 1:
                continue
            if _in_meeting_blackout():
                continue
            await _run_jang_reflection()
        except Exception as e:
            _log.warning("jang_injection_loop: unhandled error: %s", e)
