enabled: true
storage:
  snapshots_max_mb: 500
  log_max_mb: 50
cameras:
  utekamera_nedside_vest:
    display_name: utekamera_nedside_vest
    role: driveway
    labels:
      person:
        analyze: true
        min_confidence: 0.65
        announce: false
        min_duration_seconds: 0
      dog:
        analyze: false
        min_confidence: 0.65
        announce: false
      cat:
        analyze: false
        min_confidence: 0.65
        announce: false
      bicycle:
        analyze: false
        min_confidence: 0.65
        announce: false
      car:
        analyze: false
        min_confidence: 0.65
        announce: false
      license_plate:
        analyze: false
        min_confidence: 0.65
        announce: false
      deer:
        analyze: false
        min_confidence: 0.65
        announce: false
      postnord:
        analyze: false
        min_confidence: 0.65
        announce: false
  cam_ae836b98:
    display_name: cam_ae836b98
    role: driveway
    labels:
      person:
        analyze: true
        min_confidence: 0.65
        announce: false
      dog:
        analyze: false
        min_confidence: 0.65
        announce: false
      cat:
        analyze: false
        min_confidence: 0.65
        announce: false
      bicycle:
        analyze: false
        min_confidence: 0.65
        announce: false
      car:
        analyze: false
        min_confidence: 0.65
        announce: false
      license_plate:
        analyze: false
        min_confidence: 0.65
        announce: false
      deer:
        analyze: false
        min_confidence: 0.65
        announce: false
      postnord:
        analyze: false
        min_confidence: 0.65
        announce: false
  cam_a4e5b958:
    display_name: cam_a4e5b958
    role: front_door
    labels:
      person:
        analyze: true
        min_confidence: 0.65
        announce: false
      dog:
        analyze: false
        min_confidence: 0.65
        announce: false
      cat:
        analyze: false
        min_confidence: 0.65
        announce: false
      bicycle:
        analyze: false
        min_confidence: 0.65
        announce: false
      car:
        analyze: false
        min_confidence: 0.65
        announce: false
      license_plate:
        analyze: false
        min_confidence: 0.65
        announce: false
      deer:
        analyze: false
        min_confidence: 0.65
        announce: false
      postnord:
        analyze: false
        min_confidence: 0.65
        announce: false
  ringeklokke_kamera:
    display_name: ringeklokke_kamera
    role: front_door
    labels:
      person:
        analyze: true
        min_confidence: 0.65
        announce: false
      dog:
        analyze: false
        min_confidence: 0.65
        announce: false
      cat:
        analyze: false
        min_confidence: 0.65
        announce: false
      bicycle:
        analyze: false
        min_confidence: 0.65
        announce: false
      car:
        analyze: false
        min_confidence: 0.65
        announce: false
      license_plate:
        analyze: false
        min_confidence: 0.65
        announce: false
      deer:
        analyze: false
        min_confidence: 0.65
        announce: false
      postnord:
        analyze: false
        min_confidence: 0.65
        announce: false
roles:
  front_door:
    display_name: Inngangsdør
  driveway:
    display_name: Innkjørsel
  road_facing:
    display_name: Mot vei
  garden:
    display_name: Hage
  garage:
    display_name: Garasje
  indoor:
    display_name: Innendørs
  custom_1:
    display_name: ''
  custom_2:
    display_name: ''
  custom_3:
    display_name: ''
