always_included:
- selvbilde
- verden
- brukerprofil
- les_indre_tanker
- les_tankehistorikk
roles:
  child:
  - styr_enhet
  - les_ha
  - timer
  - get_weather
  - library
  - kare_image
  - se_bilder
  - media
  - notat
  - announce
  - reason_freely
  teen:
  - styr_enhet
  - les_ha
  - timer
  - get_weather
  - library
  - library_online
  - søk_nett
  - kare_image
  - se_bilder
  - media
  - notat
  - announce
  - reason_freely
  young_adult:
  - styr_enhet
  - les_ha
  - timer
  - get_weather
  - library
  - library_online
  - søk_nett
  - kare_image
  - se_bilder
  - media
  - notat
  - announce
  - reason_freely
  - minne
  adult:
  - styr_enhet
  - les_ha
  - timer
  - get_weather
  - library
  - library_online
  - søk_nett
  - kare_image
  - se_bilder
  - media
  - notat
  - announce
  - reason_freely
  - minne
  - kamera
  admin:
  - all
agent_tools:
  mechanic:
    utforsk: true
    inspiser: true
    nettsøk: true
    søk_argus: true
    shell: false
    hukommelse: true
  miss_kare:
    spør_miss_library: true
  miss_library:
    wiki: true
