"""
Kåres langtidsminne – lag 1 (working memory)

Loggfører alle interaksjoner til SQLite asynkront (fire-and-forget).
Blokkerer aldri svar-stien.

Databasefil: /kaare/state/memory/interactions.db

Skjema:
  interactions  – én rad per tur (prompt → svar + utfall)
  feedback      – oppdateres når bruker reagerer (positiv/negativ)
"""

from __future__ import annotations

import asyncio
import logging
import sqlite3
from datetime import datetime, timezone
from pathlib import Path
from typing import Optional

from kaare_core.crypto import encrypt_text, decrypt_text
from kaare_core.session_keys import get_session_key_sync

logger = logging.getLogger(__name__)

DB_PATH = Path("/kaare/state/memory/interactions.db")

USER_GLOBAL = "global"

_ENC_PREFIX = "ENC:"


def _enc(user_id: str, text: str) -> str:
    """Encrypt text for LTM storage using session key. Returns ENC:<blob> if key available, else plaintext."""
    if not text or user_id == USER_GLOBAL:
        return text
    try:
        key = get_session_key_sync(user_id)
        if key is None:
            return text
        return _ENC_PREFIX + encrypt_text(text, key)
    except Exception:
        return text


def _dec(user_id: str, text: str) -> str:
    """Decrypt ENC:-prefixed LTM text using session key. Returns [kryptert] if no session, plaintext if not encrypted."""
    if not text or not text.startswith(_ENC_PREFIX):
        return text
    try:
        key = get_session_key_sync(user_id)
        if key is None:
            return "[kryptert]"
        return decrypt_text(text[len(_ENC_PREFIX):], key)
    except Exception:
        logger.warning("LTM: decrypt failed for user %s", user_id)
        return "[kryptert]"


def _dec_row(row: dict, fields: list) -> dict:
    """Decrypt named fields in a result row using its own user_id."""
    uid = row.get("user_id", USER_GLOBAL)
    for f in fields:
        if f in row and row[f]:
            row[f] = _dec(uid, row[f])
    return row

_SCHEMA = """
CREATE TABLE IF NOT EXISTS interactions (
    id          INTEGER PRIMARY KEY AUTOINCREMENT,
    ts          TEXT    NOT NULL,
    user_id     TEXT    NOT NULL DEFAULT 'global',
    prompt      TEXT    NOT NULL,
    source      TEXT    DEFAULT '',
    intent      TEXT    DEFAULT '',
    entity_id   TEXT    DEFAULT '',
    action      TEXT    DEFAULT '',
    response    TEXT    NOT NULL DEFAULT '',
    outcome     TEXT    DEFAULT 'unknown',
    feedback    TEXT    DEFAULT 'unknown',
    model_used  TEXT    DEFAULT '',
    repaired    INTEGER DEFAULT 0,
    confidence  REAL    DEFAULT 0.5
);

CREATE INDEX IF NOT EXISTS idx_interactions_ts ON interactions(ts);
CREATE INDEX IF NOT EXISTS idx_interactions_user_id ON interactions(user_id);
CREATE INDEX IF NOT EXISTS idx_interactions_intent ON interactions(intent);
CREATE INDEX IF NOT EXISTS idx_interactions_feedback ON interactions(feedback);

-- Verifikasjonshistorikk: ett vindu per gang Kåre spør brukeren om bekreftelse.
-- from_id/to_id peker på interaksjon-IDer som dekkes av dette vinduet.
-- verdict: 'pending' → Kåre har spurt, ingen svar ennå
--          'confirmed' → bruker bekreftet at det gikk bra
--          'denied'    → bruker sa det ikke stemte
CREATE TABLE IF NOT EXISTS verifications (
    id                INTEGER PRIMARY KEY AUTOINCREMENT,
    ts_asked          TEXT    NOT NULL,
    ts_answered       TEXT,
    user_id           TEXT    NOT NULL DEFAULT 'global',
    from_id           INTEGER NOT NULL,
    to_id             INTEGER NOT NULL,
    unverified_count  INTEGER DEFAULT 0,
    verdict           TEXT    DEFAULT 'pending',
    user_text         TEXT    DEFAULT ''
);

CREATE INDEX IF NOT EXISTS idx_verifications_verdict ON verifications(verdict);
CREATE INDEX IF NOT EXISTS idx_verifications_user_id ON verifications(user_id);
CREATE INDEX IF NOT EXISTS idx_verifications_ts ON verifications(ts_asked);

-- Episodisk lag: LLM-komprimerte sammendrag av N interaksjoner.
-- Nattjobben fyller denne tabellen. Grunnlag for fremtidig Qdrant-indeksering.
CREATE TABLE IF NOT EXISTS episodes (
    id                INTEGER PRIMARY KEY AUTOINCREMENT,
    ts_created        TEXT    NOT NULL,
    user_id           TEXT    NOT NULL DEFAULT 'global',
    from_id           INTEGER NOT NULL,
    to_id             INTEGER NOT NULL,
    interaction_count INTEGER DEFAULT 0,
    narrative         TEXT    NOT NULL,
    topics            TEXT    DEFAULT '',
    confidence        REAL    DEFAULT 0.5
);

CREATE INDEX IF NOT EXISTS idx_episodes_ts ON episodes(ts_created);
CREATE INDEX IF NOT EXISTS idx_episodes_user_id ON episodes(user_id);

-- Daily compressed summary of the STM (short-term memory) — one row per user per day.
-- Generated by the nightjob at 03:00 and loaded into STM at API startup.
CREATE TABLE IF NOT EXISTS stm_daily_summary (
    id                INTEGER PRIMARY KEY AUTOINCREMENT,
    date              TEXT    NOT NULL,
    user_id           TEXT    NOT NULL DEFAULT 'global',
    summary           TEXT    NOT NULL,
    interaction_count INTEGER DEFAULT 0,
    ts_created        TEXT    NOT NULL,
    UNIQUE(date, user_id)
);

CREATE INDEX IF NOT EXISTS idx_stm_daily_summary_date ON stm_daily_summary(date);
CREATE INDEX IF NOT EXISTS idx_stm_daily_summary_user_date ON stm_daily_summary(date, user_id);

-- Intern agent-kommunikasjon: loggfører alle meldinger mellom agenter.
CREATE TABLE IF NOT EXISTS agent_messages (
    id          INTEGER PRIMARY KEY AUTOINCREMENT,
    ts          TEXT    NOT NULL,
    rid         TEXT    DEFAULT '',
    user_id     TEXT    NOT NULL DEFAULT 'global',
    from_agent  TEXT    NOT NULL,
    to_agent    TEXT    NOT NULL,
    query       TEXT    NOT NULL,
    response    TEXT    NOT NULL DEFAULT ''
);

CREATE INDEX IF NOT EXISTS idx_agent_messages_ts ON agent_messages(ts);
CREATE INDEX IF NOT EXISTS idx_agent_messages_rid ON agent_messages(rid);

-- Fallback sessions: logged each time the main 27B model was unreachable.
-- Kåre and Miss Kåre can query this to reflect on system reliability.
CREATE TABLE IF NOT EXISTS fallback_sessions (
    id          INTEGER PRIMARY KEY AUTOINCREMENT,
    ts_start    TEXT    NOT NULL,
    ts_end      TEXT    NOT NULL,
    turn_count  INTEGER DEFAULT 0
);

CREATE INDEX IF NOT EXISTS idx_fallback_sessions_ts ON fallback_sessions(ts_start);
"""

# Nøkkelord som tyder på at brukeren er misfornøyd
_NEGATIVE_PHRASES = [
    "nei", "feil", "ikke det", "galt", "feil enhet", "stopp",
    "ikke riktig", "det var ikke", "mener ikke", "mente ikke",
]

# Nøkkelord som tyder på at brukeren er fornøyd
_POSITIVE_PHRASES = [
    "takk", "perfekt", "bra", "supert", "riktig", "akkurat", "ja takk",
    "stemmer", "korrekt", "flott",
]


def _utc_ts() -> str:
    return datetime.now(timezone.utc).isoformat(timespec="seconds")


def _get_conn() -> sqlite3.Connection:
    """Åpner tilkobling med WAL-modus (trygg for concurrent access)."""
    DB_PATH.parent.mkdir(parents=True, exist_ok=True)
    conn = sqlite3.connect(str(DB_PATH), check_same_thread=False)
    conn.execute("PRAGMA journal_mode=WAL")
    conn.execute("PRAGMA synchronous=NORMAL")
    return conn


def _migrate(conn: sqlite3.Connection) -> None:
    """Legg til nye kolonner og fiks constraints i eksisterende database uten å miste data."""
    def cols(table: str) -> set:
        return {row[1] for row in conn.execute(f"PRAGMA table_info({table})").fetchall()}

    def table_exists(name: str) -> bool:
        return bool(conn.execute(
            "SELECT name FROM sqlite_master WHERE type='table' AND name=?", (name,)
        ).fetchone())

    changed = False
    existing_int = cols("interactions")
    if existing_int and "user_id" not in existing_int:
        conn.execute("ALTER TABLE interactions ADD COLUMN user_id TEXT NOT NULL DEFAULT 'global'")
        changed = True

    existing_ver = cols("verifications")
    if existing_ver and "user_id" not in existing_ver:
        conn.execute("ALTER TABLE verifications ADD COLUMN user_id TEXT NOT NULL DEFAULT 'global'")
        changed = True

    existing_ep = cols("episodes")
    if existing_ep and "user_id" not in existing_ep:
        conn.execute("ALTER TABLE episodes ADD COLUMN user_id TEXT NOT NULL DEFAULT 'global'")
        changed = True

    # Migrate stm_daily_summary: UNIQUE(date) → UNIQUE(date, user_id)
    if table_exists("stm_daily_summary"):
        indexes = {row[1] for row in conn.execute("PRAGMA index_list(stm_daily_summary)").fetchall()}
        if "idx_stm_daily_summary_user_date" not in indexes:
            conn.executescript("""
                CREATE TABLE IF NOT EXISTS stm_daily_summary_new (
                    id                INTEGER PRIMARY KEY AUTOINCREMENT,
                    date              TEXT    NOT NULL,
                    user_id           TEXT    NOT NULL DEFAULT 'global',
                    summary           TEXT    NOT NULL,
                    interaction_count INTEGER DEFAULT 0,
                    ts_created        TEXT    NOT NULL,
                    UNIQUE(date, user_id)
                );
                INSERT INTO stm_daily_summary_new (date, user_id, summary, interaction_count, ts_created)
                    SELECT date, user_id, summary, interaction_count, ts_created
                    FROM stm_daily_summary;
                DROP TABLE stm_daily_summary;
                ALTER TABLE stm_daily_summary_new RENAME TO stm_daily_summary;
                CREATE INDEX IF NOT EXISTS idx_stm_daily_summary_date ON stm_daily_summary(date);
                CREATE INDEX IF NOT EXISTS idx_stm_daily_summary_user_date ON stm_daily_summary(date, user_id);
            """)
            changed = True

    if changed:
        conn.commit()


def _init_db() -> None:
    """Oppretter tabeller hvis de ikke finnes, og kjører migration."""
    conn = _get_conn()
    try:
        _migrate(conn)          # legg til manglende kolonner FØR schema-script
        conn.executescript(_SCHEMA)
        conn.commit()
    finally:
        conn.close()


class LongTermMemory:
    """
    Asynkron langtidsminne-logger.

    Bruk:
        ltm = LongTermMemory()
        interaction_id = await ltm.log_interaction(prompt=..., source=..., ...)
        await ltm.update_response(interaction_id, response=..., outcome=...)
        await ltm.update_feedback(interaction_id, feedback="positive")

    Alt skrives i bakgrunnen – blokkerer aldri svar-stien.
    """

    def __init__(self) -> None:
        _init_db()
        self._last_id: dict[str, Optional[int]] = {}   # per user_id
        self._last_prompt: dict[str, str] = {}          # per user_id

    # -----------------------------------------------------------------------
    # Skriving (asynkron, fire-and-forget)
    # -----------------------------------------------------------------------

    async def log_interaction(
        self,
        *,
        prompt: str,
        user_id: str = USER_GLOBAL,
        source: str = "",
        intent: str = "",
        entity_id: str = "",
        action: str = "",
        model_used: str = "",
    ) -> Optional[int]:
        """
        Logger en ny interaksjon. Returnerer interaction_id.
        Skrives asynkront – kast ikke bort tid på å vente.
        """
        try:
            interaction_id = await asyncio.get_event_loop().run_in_executor(
                None,
                self._write_interaction,
                prompt, user_id, source, intent, entity_id, action, model_used,
            )
            self._last_id[user_id] = interaction_id
            self._last_prompt[user_id] = prompt
            return interaction_id
        except Exception as e:
            logger.warning("LTM: log_interaction feilet: %s", e)
            return None

    def _write_interaction(
        self,
        prompt: str,
        user_id: str,
        source: str,
        intent: str,
        entity_id: str,
        action: str,
        model_used: str,
    ) -> int:
        uid = user_id or USER_GLOBAL
        conn = _get_conn()
        try:
            cur = conn.execute(
                """INSERT INTO interactions
                   (ts, user_id, prompt, source, intent, entity_id, action, model_used, outcome, feedback)
                   VALUES (?, ?, ?, ?, ?, ?, ?, ?, 'pending', 'unknown')""",
                (_utc_ts(), uid, _enc(uid, prompt or ""), source or "",
                 intent or "", entity_id or "", action or "", model_used or ""),
            )
            conn.commit()
            return cur.lastrowid
        finally:
            conn.close()

    def mark_interactions(
        self, ids: list[int], verdict: str, user_id: str = USER_GLOBAL
    ) -> int:
        """
        Sets feedback and confidence on specific interactions.
        verdict: 'verified' | 'denied' | 'test'
        Returns number of rows updated.
        """
        if not ids:
            return 0
        confidence_map = {"verified": 0.9, "denied": 0.1, "test": 0.0}
        feedback_map = {"verified": "verified", "denied": "denied_general", "test": "test"}
        new_confidence = confidence_map.get(verdict, 0.5)
        new_feedback = feedback_map.get(verdict, verdict)
        conn = _get_conn()
        try:
            placeholders = ",".join("?" * len(ids))
            cur = conn.execute(
                f"UPDATE interactions SET feedback=?, confidence=?"
                f" WHERE id IN ({placeholders}) AND user_id=?",
                [new_feedback, new_confidence, *ids, user_id],
            )
            conn.commit()
            return cur.rowcount
        finally:
            conn.close()

    async def update_response(
        self,
        interaction_id: Optional[int],
        *,
        response: str,
        outcome: str,          # 'success' | 'error' | 'clarification' | 'llm_fallback' | 'vlm' | 'test'
        intent: str = "",
        entity_id: str = "",
        action: str = "",
        repaired: bool = False,
        model_used: str = "",
    ) -> None:
        """Oppdaterer rad med svar og utfall. Kalles etter at svar er klart."""
        if interaction_id is None:
            return
        try:
            await asyncio.get_event_loop().run_in_executor(
                None,
                self._write_response,
                interaction_id, response, outcome, intent, entity_id, action, repaired, model_used,
            )
        except Exception as e:
            logger.warning("LTM: update_response feilet: %s", e)

    def _write_response(
        self,
        interaction_id: int,
        response: str,
        outcome: str,
        intent: str,
        entity_id: str,
        action: str,
        repaired: bool,
        model_used: str,
    ) -> None:
        conn = _get_conn()
        try:
            row = conn.execute("SELECT user_id FROM interactions WHERE id=?", (interaction_id,)).fetchone()
            uid = row[0] if row else USER_GLOBAL
            conn.execute(
                """UPDATE interactions SET
                   response=?, outcome=?, intent=COALESCE(NULLIF(?, ''), intent),
                   entity_id=COALESCE(NULLIF(?, ''), entity_id),
                   action=COALESCE(NULLIF(?, ''), action),
                   repaired=?, model_used=COALESCE(NULLIF(?, ''), model_used)
                   WHERE id=?""",
                (_enc(uid, response or ""), outcome or "unknown", intent or "", entity_id or "", action or "",
                 1 if repaired else 0, model_used or "", interaction_id),
            )
            conn.commit()
        finally:
            conn.close()

    async def log_fallback_session(
        self,
        *,
        ts_start: str,
        ts_end: str,
        turn_count: int,
    ) -> None:
        """Log a completed 9B fallback session to LTM (fire-and-forget)."""
        try:
            await asyncio.get_event_loop().run_in_executor(
                None, self._write_fallback_session, ts_start, ts_end, turn_count,
            )
        except Exception as e:
            logger.warning("LTM: log_fallback_session feilet: %s", e)

    def _write_fallback_session(self, ts_start: str, ts_end: str, turn_count: int) -> None:
        conn = _get_conn()
        try:
            conn.execute(
                "INSERT INTO fallback_sessions (ts_start, ts_end, turn_count) VALUES (?, ?, ?)",
                (ts_start, ts_end, turn_count),
            )
            conn.commit()
        finally:
            conn.close()

    async def update_feedback(
        self,
        interaction_id: Optional[int],
        *,
        feedback: str,   # 'positive' | 'negative' | 'neutral'
    ) -> None:
        """Oppdaterer feedback-felt på en eksisterende interaksjon."""
        if interaction_id is None:
            return
        try:
            await asyncio.get_event_loop().run_in_executor(
                None, self._write_feedback, interaction_id, feedback,
            )
        except Exception as e:
            logger.warning("LTM: update_feedback feilet: %s", e)

    def _write_feedback(self, interaction_id: int, feedback: str) -> None:
        conn = _get_conn()
        try:
            conn.execute(
                "UPDATE interactions SET feedback=? WHERE id=?",
                (feedback, interaction_id),
            )
            conn.commit()
        finally:
            conn.close()

    # -----------------------------------------------------------------------
    # Feedback-deteksjon
    # -----------------------------------------------------------------------

    def detect_verification_response(self, prompt: str) -> Optional[str]:
        """
        Sjekker om prompten er et svar på en verifikasjonsforespørsel.
        Bruker konkrete fraser som ikke kan misforstås som action-feedback.

        Returnerer 'confirmed', 'denied', eller None.
        """
        if not prompt:
            return None
        p = prompt.lower().strip()

        _confirmed = ["det virker", "det er riktig", "det er sant", "stemmer bra", "fungerer bra", "ja det stemmer"]
        _denied    = ["ikke helt", "nei faktisk", "stemmer ikke", "det stemmer ikke", "fungerer ikke bra"]

        if any(phrase in p for phrase in _denied):
            return "denied"
        if any(phrase in p for phrase in _confirmed):
            return "confirmed"
        return None

    def detect_feedback_signal(self, prompt: str, user_id: str = USER_GLOBAL) -> Optional[str]:
        """
        Sjekker om en ny prompt inneholder signal om forrige svar.
        Returnerer 'positive', 'negative', eller None.

        Kalles FØR ny interaksjon logges, mens _last_id peker på forrige for denne brukeren.
        """
        if not prompt or not self._last_id.get(user_id):
            return None

        p = prompt.lower().strip()

        # Negativ: bruker korrigerer eller klager
        if any(phrase in p for phrase in _NEGATIVE_PHRASES):
            return "negative"

        # Gjentakelse: veldig lik forrige prompt (bruker prøver igjen)
        last_prompt = self._last_prompt.get(user_id, "")
        if last_prompt:
            prev = last_prompt.lower().strip()
            # Enkel likhet: mer enn 60% av ordene er felles
            prev_words = set(prev.split())
            curr_words = set(p.split())
            if prev_words and curr_words:
                overlap = len(prev_words & curr_words) / max(len(prev_words), len(curr_words))
                if overlap > 0.6 and p != prev:
                    return "negative"

        # Positiv: bruker bekrefter
        if any(phrase in p for phrase in _POSITIVE_PHRASES):
            return "positive"

        return None

    # -----------------------------------------------------------------------
    # Søk og lesing
    # -----------------------------------------------------------------------

    def search_interactions(
        self, query: str, limit: int = 8, user_id: Optional[str] = None
    ) -> list[dict]:
        """
        Søker i interaksjonshistorikk etter relevante episoder.
        Matcher på tvers av prompt, response, entity_id og action.
        Returnerer de N mest relevante, nyeste først.
        Enkel nøkkelord-matching — Qdrant tar over i semantisk lag.
        user_id=None søker på tvers av alle brukere.
        """
        if not query or not query.strip():
            return []

        keywords = [w.strip().lower() for w in query.split() if len(w.strip()) > 2]
        if not keywords:
            return []

        conn = _get_conn()
        try:
            conditions = []
            params: list = []

            if user_id is not None:
                conditions.append("user_id = ?")
                params.append(user_id)

            for kw in keywords:
                pattern = f"%{kw}%"
                conditions.append(
                    "(LOWER(prompt) LIKE ? OR LOWER(response) LIKE ? "
                    "OR LOWER(entity_id) LIKE ? OR LOWER(action) LIKE ?)"
                )
                params.extend([pattern, pattern, pattern, pattern])

            where = " AND ".join(conditions) if conditions else "1=1"
            params.append(limit)

            cur = conn.execute(
                f"""SELECT id, ts, user_id, prompt, intent, entity_id, action,
                           response, outcome, feedback, confidence
                    FROM interactions
                    WHERE {where}
                    ORDER BY id DESC
                    LIMIT ?""",
                params,
            )
            cols = [c[0] for c in cur.description]
            rows = [dict(zip(cols, row)) for row in cur.fetchall()]
            return [_dec_row(r, ["prompt", "response"]) for r in rows]
        finally:
            conn.close()

    def get_recent(self, limit: int = 20, user_id: Optional[str] = None) -> list[dict]:
        """
        Henter siste N interaksjoner.
        user_id=None returnerer alle brukere.
        """
        conn = _get_conn()
        try:
            if user_id is not None:
                cur = conn.execute(
                    """SELECT id, ts, user_id, prompt, intent, entity_id, action, response, outcome, feedback
                       FROM interactions WHERE user_id = ? ORDER BY id DESC LIMIT ?""",
                    (user_id, limit),
                )
            else:
                cur = conn.execute(
                    """SELECT id, ts, user_id, prompt, intent, entity_id, action, response, outcome, feedback
                       FROM interactions ORDER BY id DESC LIMIT ?""",
                    (limit,),
                )
            cols = [c[0] for c in cur.description]
            rows = [dict(zip(cols, row)) for row in cur.fetchall()]
            return [_dec_row(r, ["prompt", "response"]) for r in rows]
        finally:
            conn.close()

    async def log_agent_message(
        self,
        *,
        from_agent: str,
        to_agent: str,
        query: str,
        response: str,
        rid: str = "",
        user_id: str = USER_GLOBAL,
    ) -> None:
        try:
            await asyncio.get_event_loop().run_in_executor(
                None,
                self._write_agent_message,
                from_agent, to_agent, query, response, rid, user_id,
            )
        except Exception as e:
            logger.warning("LTM: log_agent_message feilet: %s", e)

    def _write_agent_message(
        self,
        from_agent: str,
        to_agent: str,
        query: str,
        response: str,
        rid: str,
        user_id: str,
    ) -> None:
        uid = user_id or USER_GLOBAL
        conn = _get_conn()
        try:
            conn.execute(
                """INSERT INTO agent_messages
                   (ts, rid, user_id, from_agent, to_agent, query, response)
                   VALUES (?, ?, ?, ?, ?, ?, ?)""",
                (_utc_ts(), rid or "", uid,
                 from_agent or "", to_agent or "", _enc(uid, query or ""), _enc(uid, response or "")),
            )
            conn.commit()
        finally:
            conn.close()

    def get_agent_messages(self, limit: int = 50) -> list[dict]:
        conn = _get_conn()
        try:
            cur = conn.execute(
                """SELECT id, ts, rid, user_id, from_agent, to_agent, query, response
                   FROM agent_messages ORDER BY id DESC LIMIT ?""",
                (limit,),
            )
            cols = [c[0] for c in cur.description]
            rows = [dict(zip(cols, row)) for row in cur.fetchall()]
            return [_dec_row(r, ["query", "response"]) for r in rows]
        finally:
            conn.close()

    def get_stats(self) -> dict:
        """Enkel statistikk — nyttig for debugging."""
        conn = _get_conn()
        try:
            total = conn.execute("SELECT COUNT(*) FROM interactions").fetchone()[0]
            by_outcome = conn.execute(
                "SELECT outcome, COUNT(*) FROM interactions GROUP BY outcome"
            ).fetchall()
            by_feedback = conn.execute(
                "SELECT feedback, COUNT(*) FROM interactions GROUP BY feedback"
            ).fetchall()
            return {
                "total": total,
                "by_outcome": dict(by_outcome),
                "by_feedback": dict(by_feedback),
            }
        finally:
            conn.close()

    # -----------------------------------------------------------------------
    # Verifikasjon
    # -----------------------------------------------------------------------

    def count_unverified_since_last(self, user_id: str = USER_GLOBAL) -> tuple[int, int, int]:
        """
        Teller interaksjoner med outcome=success og feedback=unknown
        siden siste verifikasjonsvindu for denne brukeren.

        Returnerer (antall_ubekreftede, from_id, to_id).
        """
        conn = _get_conn()
        try:
            row = conn.execute(
                "SELECT to_id FROM verifications WHERE user_id=? ORDER BY id DESC LIMIT 1",
                (user_id,),
            ).fetchone()
            after_id = row[0] if row else 0

            cur = conn.execute(
                """SELECT COUNT(*), MIN(id), MAX(id) FROM interactions
                   WHERE id > ? AND user_id = ? AND outcome = 'success' AND feedback = 'unknown'""",
                (after_id, user_id),
            )
            count, from_id, to_id = cur.fetchone()
            return (count or 0, from_id or 0, to_id or 0)
        finally:
            conn.close()

    def open_verification(self, from_id: int, to_id: int, count: int, user_id: str = USER_GLOBAL) -> Optional[int]:
        """
        Oppretter en verifikasjonsrad med verdict='pending'.
        Returnerer verifikasjons-ID.
        """
        conn = _get_conn()
        try:
            cur = conn.execute(
                """INSERT INTO verifications (ts_asked, user_id, from_id, to_id, unverified_count, verdict)
                   VALUES (?, ?, ?, ?, ?, 'pending')""",
                (_utc_ts(), user_id, from_id, to_id, count),
            )
            conn.commit()
            return cur.lastrowid
        except Exception as e:
            logger.warning("LTM: open_verification feilet: %s", e)
            return None
        finally:
            conn.close()

    def close_verification(
        self, verification_id: int, verdict: str, user_text: str = ""
    ) -> None:
        """
        Oppdaterer verifikasjonsvinduet med brukerens svar.
        verdict: 'confirmed' | 'denied'
        Justerer confidence på interaksjonene i vinduet.
        """
        conn = _get_conn()
        try:
            uid_row = conn.execute("SELECT user_id FROM verifications WHERE id=?", (verification_id,)).fetchone()
            uid = uid_row[0] if uid_row else USER_GLOBAL
            conn.execute(
                """UPDATE verifications
                   SET verdict=?, ts_answered=?, user_text=?
                   WHERE id=?""",
                (verdict, _utc_ts(), _enc(uid, user_text), verification_id),
            )
            # Juster confidence på interaksjonene i vinduet
            new_confidence = 0.9 if verdict == "confirmed" else 0.1
            row = conn.execute(
                "SELECT from_id, to_id FROM verifications WHERE id=?",
                (verification_id,),
            ).fetchone()
            if row:
                conn.execute(
                    """UPDATE interactions SET confidence=?
                       WHERE id BETWEEN ? AND ? AND outcome='success' AND feedback='unknown'""",
                    (new_confidence, row[0], row[1]),
                )
                # Merk feedback på samme vindu
                new_feedback = "verified" if verdict == "confirmed" else "denied_general"
                conn.execute(
                    """UPDATE interactions SET feedback=?
                       WHERE id BETWEEN ? AND ? AND outcome='success' AND feedback='unknown'""",
                    (new_feedback, row[0], row[1]),
                )
            conn.commit()
        except Exception as e:
            logger.warning("LTM: close_verification feilet: %s", e)
        finally:
            conn.close()

    def get_pending_verification(self, user_id: str = USER_GLOBAL) -> Optional[dict]:
        """Returnerer åpent verifikasjonsvindu for denne brukeren, eller None."""
        conn = _get_conn()
        try:
            row = conn.execute(
                """SELECT id, ts_asked, from_id, to_id, unverified_count
                   FROM verifications WHERE verdict='pending' AND user_id=?
                   ORDER BY id DESC LIMIT 1""",
                (user_id,),
            ).fetchone()
            if not row:
                return None
            return {
                "id": row[0], "ts_asked": row[1],
                "from_id": row[2], "to_id": row[3], "count": row[4],
            }
        finally:
            conn.close()

    def get_unverified_interactions(
        self, user_id: str = USER_GLOBAL, limit: int = 10, offset: int = 0
    ) -> list[dict]:
        """
        Returns unverified interactions (feedback='unknown', outcome='success').
        Ordered oldest first so reviews progress chronologically.
        """
        conn = _get_conn()
        try:
            rows = conn.execute(
                """SELECT id, ts, prompt, response FROM interactions
                   WHERE user_id = ? AND outcome = 'success' AND feedback = 'unknown'
                   ORDER BY id ASC
                   LIMIT ? OFFSET ?""",
                (user_id, limit, offset),
            ).fetchall()
            return [
                {
                    "id": r[0],
                    "ts": r[1],
                    "prompt": _dec(user_id, r[2])[:200],
                    "response": _dec(user_id, r[3])[:300],
                }
                for r in rows
            ]
        finally:
            conn.close()

    def get_verification_stats(self) -> dict:
        """Statistikk over verifikasjonshistorikk."""
        conn = _get_conn()
        try:
            total = conn.execute("SELECT COUNT(*) FROM verifications").fetchone()[0]
            by_verdict = dict(conn.execute(
                "SELECT verdict, COUNT(*) FROM verifications GROUP BY verdict"
            ).fetchall())
            avg_confidence = conn.execute(
                "SELECT AVG(confidence) FROM interactions WHERE confidence != 0.5"
            ).fetchone()[0]
            return {
                "total_verifications": total,
                "by_verdict": by_verdict,
                "avg_confidence_verified": round(avg_confidence, 3) if avg_confidence else None,
            }
        finally:
            conn.close()


# Singleton – deles av hele prosessen
_ltm: Optional[LongTermMemory] = None


def get_ltm() -> LongTermMemory:
    global _ltm
    if _ltm is None:
        _ltm = LongTermMemory()
    return _ltm


# ---------------------------------------------------------------------------
# STM daily summary – standalone helpers (used by nightjob + api startup)
# ---------------------------------------------------------------------------

def save_daily_summary(date: str, summary: str, interaction_count: int, user_id: str = USER_GLOBAL) -> None:
    """Save a daily STM summary. Called by the nightjob at 03:00."""
    conn = _get_conn()
    try:
        conn.execute(
            """INSERT OR REPLACE INTO stm_daily_summary (date, user_id, summary, interaction_count, ts_created)
               VALUES (?, ?, ?, ?, ?)""",
            (date, user_id, _enc(user_id, summary), interaction_count,
             datetime.now(timezone.utc).isoformat(timespec="seconds")),
        )
        conn.commit()
    except Exception as e:
        logger.warning("save_daily_summary failed: %s", e)
    finally:
        conn.close()


def load_latest_daily_summary(user_id: str = USER_GLOBAL) -> str:
    """Return the most recent STM daily summary for a user, or empty string."""
    conn = _get_conn()
    try:
        row = conn.execute(
            "SELECT summary FROM stm_daily_summary WHERE user_id = ? ORDER BY date DESC LIMIT 1",
            (user_id,),
        ).fetchone()
        return _dec(user_id, row[0]) if row else ""
    except Exception as e:
        logger.warning("load_latest_daily_summary failed: %s", e)
        return ""
    finally:
        conn.close()


def load_recent_daily_summaries(days: int = 3) -> list[dict]:
    """Return the last N daily summaries as list of {date, summary, interaction_count}."""
    conn = _get_conn()
    try:
        rows = conn.execute(
            """SELECT date, user_id, summary, interaction_count
               FROM stm_daily_summary
               ORDER BY date DESC LIMIT ?""",
            (days,),
        ).fetchall()
        return [{"date": r[0], "summary": _dec(r[1], r[2]), "count": r[3]} for r in rows]
    except Exception as e:
        logger.warning("load_recent_daily_summaries failed: %s", e)
        return []
    finally:
        conn.close()


def migrate_user_ltm(user_id: str) -> int:
    """Encrypt all plaintext LTM rows for a user using their current session key.

    Must be called while the user has an active session (session key in RAM).
    Idempotent — rows already prefixed with ENC: are skipped.
    Returns number of rows encrypted. Fires quickly for system accounts.
    """
    if user_id == USER_GLOBAL:
        return 0
    key = get_session_key_sync(user_id)
    if key is None:
        logger.info("LTM migrate: no session key for %s — skipping", user_id)
        return 0

    count = 0
    conn = _get_conn()
    try:
        # interactions: prompt + response
        for row_id, prompt, response in conn.execute(
            "SELECT id, prompt, response FROM interactions WHERE user_id=?", (user_id,)
        ).fetchall():
            new_prompt = _enc(user_id, prompt) if prompt and not prompt.startswith(_ENC_PREFIX) else prompt
            new_resp = _enc(user_id, response) if response and not response.startswith(_ENC_PREFIX) else response
            if new_prompt != prompt or new_resp != response:
                conn.execute("UPDATE interactions SET prompt=?, response=? WHERE id=?",
                             (new_prompt, new_resp, row_id))
                count += 1

        # agent_messages: query + response
        for row_id, query, response in conn.execute(
            "SELECT id, query, response FROM agent_messages WHERE user_id=?", (user_id,)
        ).fetchall():
            new_q = _enc(user_id, query) if query and not query.startswith(_ENC_PREFIX) else query
            new_r = _enc(user_id, response) if response and not response.startswith(_ENC_PREFIX) else response
            if new_q != query or new_r != response:
                conn.execute("UPDATE agent_messages SET query=?, response=? WHERE id=?",
                             (new_q, new_r, row_id))
                count += 1

        # stm_daily_summary: summary
        for row_id, summary in conn.execute(
            "SELECT id, summary FROM stm_daily_summary WHERE user_id=?", (user_id,)
        ).fetchall():
            if summary and not summary.startswith(_ENC_PREFIX):
                conn.execute("UPDATE stm_daily_summary SET summary=? WHERE id=?",
                             (_enc(user_id, summary), row_id))
                count += 1

        # verifications: user_text
        for row_id, user_text in conn.execute(
            "SELECT id, user_text FROM verifications WHERE user_id=?", (user_id,)
        ).fetchall():
            if user_text and not user_text.startswith(_ENC_PREFIX):
                conn.execute("UPDATE verifications SET user_text=? WHERE id=?",
                             (_enc(user_id, user_text), row_id))
                count += 1

        # episodes: narrative + topics (written by nightjob but encrypted here for completeness)
        for row_id, narrative, topics in conn.execute(
            "SELECT id, narrative, topics FROM episodes WHERE user_id=?", (user_id,)
        ).fetchall():
            new_n = _enc(user_id, narrative) if narrative and not narrative.startswith(_ENC_PREFIX) else narrative
            new_t = _enc(user_id, topics) if topics and not topics.startswith(_ENC_PREFIX) else topics
            if new_n != narrative or new_t != topics:
                conn.execute("UPDATE episodes SET narrative=?, topics=? WHERE id=?",
                             (new_n, new_t, row_id))
                count += 1

        conn.commit()
        if count:
            logger.info("LTM migrate: encrypted %d rows for %s", count, user_id)
        return count
    except Exception as e:
        logger.warning("LTM migrate: failed for %s: %s", user_id, e)
        return 0
    finally:
        conn.close()
